import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { request } from "../lib/datocms";

const HOMEPAGE_QUERY = `query HomePage($limit: IntType, $maxH: IntType, $maxW: IntType ) {
  allPhotos(first: $limit) {
    location
    image {
      url(imgixParams: {maxH: $maxH, maxW: $maxW})
    }
  }
}`;

export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY,
    variables: {
      limit: 10,
      maxH: 1920,
      maxW: 1080
    }
  });
  return {
    props: { data }
  };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          data.allPhotos.map((item, key) => {
            return (
              <article className={styles.photo}>
                <img src={item.image.url} className={styles.image} />
                <p className={styles.location}>
                  {item.location}
                </p>
              </article>
            )
          })
        }
      </main>

      <footer className={styles.footer}>
        <a href="https://fmjansen.com" rel="noopener noreferrer">
          Floris Jansen
        </a>
      </footer>
    </div>
  )
}
